# Generated by Django 5.2.5 on 2026-04-20 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0005_game_alter_rooms_max_capacity_question'),
    ]

    operations = [
        migrations.AddField(
            model_name='rooms',
            name='current_turn_index',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='rooms',
            name='last_action_text',
            field=models.TextField(blank=True),
        ),
    ]
