# Generated by Django 5.2.5 on 2026-04-30 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0006_rooms_current_turn_index_rooms_last_action_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='game_type',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='rooms',
            name='game_type',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
