# Generated by Django 5.2.5 on 2026-05-01 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0007_room_game_type_rooms_game_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='rooms',
            name='last_host_heartbeat',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
