# Generated by Django 5.2.5 on 2026-05-01 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0008_rooms_last_host_heartbeat'),
    ]

    operations = [
        migrations.AddField(
            model_name='rooms',
            name='turn_index',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
