# Generated by Django 5.2.5 on 2026-05-01 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0010_chatmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='rooms',
            name='current_scores',
            field=models.JSONField(default=dict),
        ),
    ]
