# Generated by Django 5.2.5 on 2026-05-02 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0011_rooms_current_scores'),
    ]

    operations = [
        migrations.AddField(
            model_name='rooms',
            name='last_winner',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='rooms',
            name='total_scores',
            field=models.JSONField(default=dict),
        ),
    ]
