# Generated by Django 5.2.5 on 2026-05-02 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0012_rooms_last_winner_rooms_total_scores'),
    ]

    operations = [
        migrations.AddField(
            model_name='rooms',
            name='voted_users',
            field=models.JSONField(default=list),
        ),
    ]
