# Generated by Django 5.2.5 on 2026-05-04 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0015_profile_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='dares_remaining',
            field=models.IntegerField(default=5),
        ),
        migrations.AddField(
            model_name='player',
            name='truth_streak',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='player',
            name='truths_remaining',
            field=models.IntegerField(default=5),
        ),
    ]
