# Generated by Django 5.2.5 on 2026-07-15 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0016_player_dares_remaining_player_truth_streak_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='latest_proof_url',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
