# Generated by Django 5.2.5 on 2026-07-15 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0017_chatmessage_latest_proof_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='rooms',
            name='latest_proof_url',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
