# Generated by Django 5.2.5 on 2026-07-15 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0018_rooms_latest_proof_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='rooms',
            name='voted_item_type',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='rooms',
            name='voting_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='rooms',
            name='voting_no_users',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='rooms',
            name='voting_yes_users',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
