# Generated by Django 5.2.5 on 2026-07-15 15:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0019_rooms_voted_item_type_rooms_voting_active_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chatmessage',
            old_name='latest_proof_url',
            new_name='file_url',
        ),
    ]
