# Generated by Django 5.2.5 on 2026-07-17 11:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0020_rename_latest_proof_url_chatmessage_file_url'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DevilsPokerSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p1_hand', models.CharField(default='', max_length=50)),
                ('p2_hand', models.CharField(default='', max_length=50)),
                ('p1_active_indices', models.CharField(default='0,1,2,3,4', max_length=50)),
                ('p2_active_indices', models.CharField(default='0,1,2,3,4', max_length=50)),
                ('stage', models.CharField(choices=[('SETUP', 'Setup Phase'), ('GUESSING', 'Guessing Phase'), ('PENALTY', 'Truth Penalty Phase'), ('FINISHED', 'Game Over')], default='SETUP', max_length=20)),
                ('active_penalty_question', models.TextField(blank=True, null=True)),
                ('current_turn', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='poker_turns', to=settings.AUTH_USER_MODEL)),
                ('player1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='poker_p1', to=settings.AUTH_USER_MODEL)),
                ('player2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='poker_p2', to=settings.AUTH_USER_MODEL)),
                ('room', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='poker_session', to='game.room')),
                ('winner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='poker_wins', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
