# Generated by Django 5.2.5 on 2026-07-17 11:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0021_devilspokersession'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devilspokersession',
            name='room',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='poker_session', to='game.rooms'),
        ),
    ]
