# Generated by Django 5.2.5 on 2026-07-17 12:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0022_alter_devilspokersession_room'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='devilspokersession',
            name='current_turn',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='poker_turns', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='devilspokersession',
            name='player1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='poker_p1', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='devilspokersession',
            name='player2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='poker_p2', to=settings.AUTH_USER_MODEL),
        ),
    ]
